### ISSUE TITLE
python2-pyqt4 latest breaks myrdp

### ISSUE THREAD

**Issue by khallZD** [devqore/myrdp#14]
python2-pyqt4 version 4.12.3-1 (updated in AUR 12/12/2018) breaks myrdp. When trying to launch from the command line I get 

Traceback (most recent call last):
  File "/usr/share/myrdp/main.py", line 5, in <module>
    from PyQt4.QtCore import Qt, QFile
ImportError: No module named sip

Tried reinstalling the python dependencies but still getting the error. Just wanted to give you a heads up. Keep up the great work man.

**Comment by mac-linux-free** [comment]
same here

**Comment by devqore** [comment]
Damn, this is not first time when this problem shows up with sip, but earlier was workaround to remove `python2-pyqt5` and the problem disappeared. 

This is not the problem with myrdp, but with whole framework, because it could be tested with single command line:
```
python2 -c "from PyQt4 import QtCore"
```

I will try to find some solution for that, but at this time as workaround could be used latest binary from releases:

```
wget -c https://github.com/devqore/myrdp/releases/download/2018.2.0/myrdp-2018.2.0.tar.bz2
tar -xvf myrdp-2018.2.0.tar.bz2 myrdp-2018.2.0/
./myrdp-2018.2.0/myrdp
```

**Comment by khallZD** [comment]
Thanks man

**Comment by devqore** [comment]
Ok, so following comments in https://aur.archlinux.org/packages/python2-pyqt4/ looks like package python2-pyqt4 is wrongly compiled and I suppose that will be fixed soon, at this time I checked workaround from latest comment of inemum:

>  inemum commented on 2018-12-14 03:15
Here are a couple of PKGBUILDs for the sip module: https://gitlab.com/inemum/inemum_archlinux/raw/master/python-sip-pyqt4/PKGBUILD and https://gitlab.com/inemum/inemum_archlinux/raw/master/python2-sip-pyqt4/PKGBUILD

So as the workaround (until package will be fixed) could be done something like this:
```
mkdir python2-sip-pyqt4
cd python2-sip-pyqt4/
wget -c https://gitlab.com/inemum/inemum_archlinux/raw/master/python2-sip-pyqt4/PKGBUILD
makepkg -i
```
Then command (and myrdp) `python2 -c "from PyQt4 import QtCore"` should work again :)

So right now I'm closing this issue, because this is not dependent from me. Maybe I will try to migrate pyqt4 to pyqt5 which is in main arch repo, but when I tried pyqt5 3 years ago (b7476ac95e126b133ab1552e75fe6c2ad7f9ae93) then pyqt5 doesn't work too good.
